#pragma once

#include <cassert>
#include <algorithm>
#include <array>
#include <tuple>
#include <queue>
#include <random>
#include <map>
#include <string>
#include <iostream>
#include <fstream>
#include <mutex>
#include <thread>
#include <vector>
#include <cstdlib>
#include <atomic>
#include <iostream>
#include <regex>

using std::cout;
using std::endl;
using std::string;
using std::array;
using std::map;
using std::string;
using std::ifstream;
using std::ofstream;
using std::mutex;
using std::recursive_mutex;
using std::thread;
using std::vector;
using std::regex;
using std::atomic;
using std::tuple;
using std::pair;